Исключение вылетить может, но программа вернется в состояние как будто операция, вызвавшая исключение не была вызвана